# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Majid Daliri
title: Senior Bachelor Student of University of Tehran
email: majiddl.2099@gmail.com
website: https://majiddaliri.github.io/

# Social links
twitter_username: daliri__majid
github_username:  MajidDaliri
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: daliri__majid
linkedin_username: daliri__majid
# pinterest_username: jekyll
youtube_username: daliri__majid
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My ultimate career goal is to be a world-class researcher in Computer Science and solve real-world problems. To achieve these goals, I joined the Computer Engineering Department of the University of Tehran, the highest-ranked engineering school in Iran, to study towards my bachelor’s degree. During my bachelor studies, my goal was to develop strong computer science fundamentals, explore research areas, choose a few areas for my future graduate study research career, and learn to do academic research. Furthermore, I want to maintain and develop my work ethic and problem-solving skills by being successful in every course I’ve taken during my studies.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
